api_app/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import PokemonViewSet, TypeViewSet, UserViewSet, CurrentUserView

router = DefaultRouter()
router.register('pokemon', PokemonViewSet, basename='pokemon' ) # register the pokemon
router.register('users', UserViewSet, basename='users')
router.register('type', TypeViewSet, basename='type')

urlpatterns = router.urls + [
    path('currentuser/', CurrentUserView.as_view()),
]

pokedex_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api_app.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

users/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

api_app/models.py
from django.db import models

# Create your models here.

pokemon/models.py
from django.db import models
from django.contrib.auth import get_user_model

# consider adding an ImageField, per https://docs.djangoproject.com/en/3.2/ref/models/fields/#imagefield &  https://www.geeksforgeeks.org/imagefield-django-models/

class Pokemon(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=200)
    height = models.FloatField()
    weight = models.FloatField()
    image_front = models.URLField()
    image_back = models.URLField()
    caught_by = models.ManyToManyField(get_user_model(), related_name='caught') # odd that here, Nick's required blank=True
    # types = the set of Types associated with that Pokemon

    def __str__(self):
        return self.name 
    
    # # just for fun, FAILED ATTEMPT to add the density field here, ~10-min and switching to doing it in the views.py or serializers.py
    # density = models.FloatField(default=(weight)/(height))
    
    # def __init__(self):
    #     self.calc_density(self)

    # def calc_density(self):
    #     self.density = self.weight/self.height

class Type(models.Model):
    type = models.CharField(max_length=50)
    pokemon = models.ManyToManyField(Pokemon, related_name='types')

    def __str__(self):
        return self.type

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass
    # caught = the set of Pokemon associated with that user

    # This is where you would add additional fields.
    # These will be in the DB alongside username, email, etc

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')

api_app/views.py
from rest_framework import generics, viewsets
from django.contrib.auth import get_user_model

from pokemon.models import Pokemon, Type
from .serializers import PokemonSerializer, UserSerializer, TypeSerializer
from .permissions import IsAuthorOrReadOnly, AllowAny

# UserViewSet, PokeMonViewSet, CurrentUserView? . . . 
class PokemonViewSet(viewsets.ModelViewSet):
    queryset = Pokemon.objects.all()
    serializer_class = PokemonSerializer
    permission_class = [AllowAny]
    # NOTE: above permission_class should be [IsAuthorOrReadOnly] ???

    # DENSITY ATTEMPT: This is a better way of doing it than vua Vue on the front end, but still is pretty poor compared to adding the field to the database once...
    # print(f"running class PokemonViewSet(viewsets.ModelViewSet:) section 'for object in queryset:'")
    # for object in queryset:
    #     # print(object.height)
    #     object.density = object.height / object.weight
    #     # print(object.density)

class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer
    


class TypeViewSet(viewsets.ModelViewSet):
    queryset = Type.objects.all()
    serializer_class = TypeSerializer

# not necessary below? :
class CurrentUserView(generics.RetrieveAPIView):
    serializer_class = UserSerializer
    def get_object(self):
        return self.request.user

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# merritt drf-blog: 
    # from rest_framework import generics, viewsets
    # from django.contrib.auth import get_user_model

    # from posts.models import Post
    # from .serializers import PostSerializer, UserSerializer
    # from .permissions import IsAuthorOrReadOnly

    # class PostViewSet(viewsets.ModelViewSet):
    #     queryset = Post.objects.all()
    #     serializer_class = PostSerializer
    #     permission_classes = [IsAuthorOrReadOnly]

    # class UserViewSet(viewsets.ReadOnlyModelViewSet):
    #     queryset = get_user_model().objects.all()
    #     serializer_class = UserSerializer

    # class CurrentUserView(generics.RetrieveAPIView):
    #     serializer_class = UserSerializer
    #     def get_object(self):
    #         return self.request.user

    # # class PostList(generics.ListCreateAPIView):
    # #     queryset = Post.objects.all()
    # #     serializer_class = PostSerializer
    # #     permission_classes = [IsAuthorOrReadOnly]

    # # class PostDetail(generics.RetrieveUpdateDestroyAPIView):
    # #     queryset = Post.objects.all()
    # #     serializer_class = PostSerializer
    # #     permission_classes = [IsAuthorOrReadOnly]

pokemon/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

templates/home.html
{% load static %}
<title>Pokedex 2021, by Fial Consulting</title>
<!-- https://github.com/PdxCodeGuild/class_salmon/blob/main/4%20Django/labs/lab07-pokedex.md
 -->

<header>

    {% if user.is_authenticated %}
    <h1>Welcome {{ user.username }}!</h1>
    <p><a href="{% url 'logout' %}">Logout</a><p>
    {% else %}
    <h3>Welcome, visitor!</h3>
    <p>You are not logged in. <a href="{% url 'login' %}">Login</a> <a href="{% url 'users:signup' %}">Sign Up</a></p>
    {% endif %}
</header>

<div id="vue_app">
    
    {% csrf_token %}
    
    <div id="newdiv!">

{% comment %} 
THIS IS A DJANGO COMMENT SECTION, ANY CODE WILL NOT APPEAR TO VUE OR THE BROWSER:

TODO:
    -- make an image_front and image_back alt="" text like :alt="'image_back for' [[ pokemon.name ]]"
    -- ORDER by density!
    -- add colors / styles
    -- add add new pokemon form
    -- add edit new pokemon page detail.html
    -- add types / caught_by
    -- 

{% endcomment %}

        <div v-for="pokemon in pokemon_list" :key="pokemon.id">
                <h2>
                    [[ pokemon.number ]]: [[ pokemon.name ]]
                </h2>
                <ul>    
                    <li>Height: [[ pokemon.height ]] </li>
                    <li>Weight: [[ pokemon.weight ]] </li>
                    <!-- <li>density: [[pokemon.density ]] </li> -->
                    <li>Density : [[ pokemon.weight / pokemon.height ]] </li>
                    
                <!-- TEMPORARILY COMMENTED OUT FOR QUICKER PAGE LOADING: -->
                    <!-- <img :src="[[ pokemon.image_front ]]" > -->
                    <!-- <img :src="[[ pokemon.image_back ]]" > -->

                    <!-- BLANK FOR NOW: -->
                    <!-- <li>caught_by: [[ pokemon.caught_by ]] </li> -->
                    <!-- <li>types: [[ pokemon.types ]] </li> -->
                </ul>
            {% comment %} <h3>            </h3> {% endcomment %}
        </div>
    </div>
    
    <footer>
        nothing in the footer for nowsies
    </footer>
</div> <!-- END VUE.JS DIV ID="vue_app" -->

<script src="https://unpkg.com/axios/dist/axios.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js" ></script>
<!-- add the vue_app.js file... -->
<link rel="stylesheet" href="{% static '/main.css' %}">
<script src="{% static '/vue_app.js' %}"></script>